defaults: &defaults
  # Rails secret  token `rake secret`
  secret_key_base: 'b36b157a9d227002305cb35d6da2e87855be91ae12c338cb508a30f4cf15dfc91d3c5a48f44e45e75ffb5fa8069cac7ef3c297518aa75a1af048b9e8bb0c5efc'
  # Mailgun Api key to validate emails
  # Can put a list of api keys
  mailboxlayer_api_key: 'pubkey'
  # Bugsnag
  bugsnag_api_key: 'apikey'
  #Analytics
  analytics_id: 'UA-XXXXXXXX-X'
  # gdrive details https://developers.google.com/drive/web/auth/web-server
  gdrive:
    json: <%= Rails.root.join('certs', 'gdrive.json') %>
    roles:
      owner: [owner@gmail.com]
      writer: [writer@gmail.com, writer2@gmail.com]
  telegram:
    token: ''
    chat_id: ''
  trusted_sites:
    some_site: CUSTOM_HEADER # added by apache/nginx

development:
  <<: *defaults
production:
  <<: *defaults
test:
  <<: *defaults
